#ifndef __DEFINES__
#define __DEFINES__

#define MICROFOCUS_DATA_DIR "C:\\cvi Applications\\Microfocus - Components\\Microfocus Data\\"

//#define POWER_STANDALONE_ENABLED
//#define SHUTTER_STANDALONE_ENABLED
//#define EPICUBE_STANDALONE_ENABLED
//#define FLUOR_CUBE_STANDALONE_ENABLED
//#define HG_LAMP_STANDALONE_ENABLED
//#define EPI_LAMP_STANDALONE_ENABLED
//#define XYZ_STANDALONE_ENABLED
//#define ELECTRON_BEAM_SOURCE_STANDALONE_ENABLED
//#define TURRETZ_STANDALONE_ENABLED
#define OBJECTIVE_STANDALONE_ENABLED

#endif
