MACRO (GET_UIR_FILES FILE_SRCS)

SET(UIR_FILES "")

FOREACH(SRC_FILE ${FILE_SRCS})
    GET_FILENAME_COMPONENT(ext ${SRC_FILE} EXT)
    
    IF("${ext}" MATCHES "^uir$")
    LIST(APPEND UIR_FILES "${SRC_FILE}")
    ENDIF("${ext}" MATCHES "^uir$")
    
ENDFOREACH(SRC_FILE)

ENDMACRO(GET_UIR_FILES)