INCLUDE(MAKE_WINDOWS_PATH)

FIND_PATH (HARDWARE_DIR_PATH Shutter ${MICROSCOPY_TOPLEVEL_SOURCE_DIR}/../../../../ATD_Hardware NO_DEFAULT_PATH)

IF (HARDWARE_DIR_PATH-NOTFOUND)
    MESSAGE(FATAL_ERROR "Could not find Hardware")
ENDIF (HARDWARE_DIR_PATH-NOTFOUND)

IF (USE_90I_COMPONENTS)
SET(APERATURE_STOP_SRCS 	
                        ${HARDWARE_DIR_PATH}/ApertureStop/trunk/90i_aperture_stop.c
                        ${HARDWARE_DIR_PATH}/ApertureStop/trunk/90i_aperture_stop.h
)
ENDIF (USE_90I_COMPONENTS)

INCLUDE_DIRECTORIES(${HARDWARE_DIR_PATH}/ApertureStop/trunk/)
            
ADD_DEFINITIONS(-D BUILD_MODULE_APERATURE_STOP)
            
SOURCE_GROUP("Hardware\\ApertureStop" FILES ${APERATURE_STOP_SRCS})